### ISSUE TITLE
rubocop complains about space after #

### ISSUE THREAD

**Issue by jsirex** [realityforge/knife-cookbook-doc#18]
```ruby
Running RuboCop...
Inspecting 6 files
...C..

Offenses:

recipes/default.rb:1:1: C: Missing space after #.
#<> Test
^^^^^^^^

6 files inspected, 1 offense detected
RuboCop failed!
```

Disabling this cop in whole project - bad idea. Disabling explicitly each document section can be annoying. May be use something different as doc marker:
```ruby
# :chef-doc: Single line description

# :chef-doc:
# Some long
# multi-line
# description
```

Also whole comment section can be interpreted as documentation comment. No need to do '#<' - comment open and '#>' comment close. Empty line separates it:
```ruby
# :chef-doc:
# Long documentation
# with multi-line
# feature

# But this is just comment
```

For attributes:

```ruby
# :chef-attr: Default port used by service
default['service']['port'] = 5559
# :chef-skip:
default['service']['bind_addr'] = '0.0.0.0'  # don't want this attribute be in docs
```

**Comment by realityforge** [comment]
This seems like a very reasonable request. The code could probably be fixed so that it supports both forms and probably warns on the old variant for some period of time. 

I would love to implement this but don't have the cycles to do so atm. I would gladly accept pull requests if you have the time :)

**Comment by tmaier** [comment]
+1 on the idea.

The comment format used by `knife-cookbook-doc` is actually the main blocking issue for me to use it.

**Comment by ikurochkin** [comment]
+1

**Comment by philoserf** [comment]
PR#25 might cover this. It isn't the proposed solution. Only my independent resolution from the same motive.

**Comment by realityforge** [comment]
I believe this is fixed by #25 - thanks to @philoserf

**Comment by ThatGerber** [comment]
This PR only works for comment blocks. Single line commens `# <> @attribute name Description` is still not being picked up by cookbook doc.
